"""Add receives_notification to User

Revision ID: 10f21a303d6e
Revises: 027bd63b5ce7
Create Date: 2025-11-24 17:03:42.857849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f21a303d6e'
down_revision: Union[str, Sequence[str], None] = '027bd63b5ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('receives_notification', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'receives_notification')
    # ### end Alembic commands ###
