"""Add display_message and rejection_reason to reservations

Revision ID: 5b7a408ca051
Revises: 6c3c3ef70a7b
Create Date: 2025-11-24 14:30:29.728100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7a408ca051'
down_revision: Union[str, Sequence[str], None] = '6c3c3ef70a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('display_message', sa.String(length=255), nullable=True))
    op.add_column('reservations', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'rejection_reason')
    op.drop_column('reservations', 'display_message')
    # ### end Alembic commands ###
