"""Add approval_message to reservations

Revision ID: a596faa3deb0
Revises: 88ed45e9fa96
Create Date: 2025-11-24 14:53:19.078492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a596faa3deb0'
down_revision: Union[str, Sequence[str], None] = '88ed45e9fa96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('approval_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'approval_message')
    # ### end Alembic commands ###
