"""Add cancellation_reason

Revision ID: f66e89c00f83
Revises: a596faa3deb0
Create Date: 2025-11-24 15:46:30.579813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66e89c00f83'
down_revision: Union[str, Sequence[str], None] = 'a596faa3deb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'cancellation_reason')
    # ### end Alembic commands ###
